# Generated by Django 3.2 on 2021-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movietable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=20)),
                ('hero', models.CharField(max_length=20)),
                ('heroine', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'movietable',
                'verbose_name_plural': 'movietables',
            },
        ),
    ]
