# Generated by Django 3.2 on 2021-12-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
