# Generated by Django 3.2 on 2021-05-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jersey_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('ipl_team', models.CharField(max_length=50)),
            ],
        ),
    ]
